name: MinGW

on:
  push:
    branches: [ main ]
    paths-ignore:
    - 'docs/**'
    - 'assets/**'
    - '.gitattributes'
    - '.gitignore'
    - 'LICENSE'
    - 'README.md'
    - '.github/workflows/ms-build.yml'
    - '.github/workflows/ubuntu-build.yml'
    - '.github/workflows/macos-build.yml'
  pull_request:
    branches: [ main ]
    paths-ignore:
    - 'docs/**'
    - 'assets/**'
    - '.gitattributes'
    - '.gitignore'
    - 'LICENSE'
    - 'README.md'
    - '.github/workflows/ms-build.yml'
    - '.github/workflows/ubuntu-build.yml'
    - '.github/workflows/macos-build.yml'

jobs:
  build:
    runs-on: windows-latest

    strategy:
      fail-fast: false  # if a particular matrix build fails, don't skip the rest
      matrix:
        arch: ["x64"]  # disable x86 build for now, because it's too time consuming
        #arch: ["x86", "x64"]

    steps:
    - uses: actions/checkout@v2

    - name: Set up MinGW
      uses: egor-tensin/setup-mingw@v2
      with:
        platform: ${{ matrix.arch }} 

    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9

    - name: Build source and tests
      run: python3 build.py --build-tests --arch=${{matrix.arch}}
    
    - name: Run tests
      run: python3 build.py --run-tests --arch=${{matrix.arch}}
    
    - name: Check dist
      run: |
        .\\dist\\MinGW-${{matrix.arch}}\\kcr.exe -V
        .\\dist\\MinGW-${{matrix.arch}}\\kcr.exe --lex test\\test_script.kh

    #- name: Upload dist
      #uses: actions/upload-artifact@v2
      #with:
        #name: dist-MinGW
        #path: dist/
