name: MinGW

on:
  push:
    branches: [ main ]
    paths-ignore:
    - 'docs/**'
    - 'assets/**'
    - '.gitattributes'
    - '.gitignore'
    - 'LICENSE'
    - 'README.md'
    - '.github/workflows/ms-build.yml'
    - '.github/workflows/ubuntu-build.yml'
    - '.github/workflows/macos-build.yml'
  pull_request:
    branches: [ main ]
    paths-ignore:
    - 'docs/**'
    - 'assets/**'
    - '.gitattributes'
    - '.gitignore'
    - 'LICENSE'
    - 'README.md'
    - '.github/workflows/ms-build.yml'
    - '.github/workflows/ubuntu-build.yml'
    - '.github/workflows/macos-build.yml'

jobs:
  build:
    runs-on: windows-latest

    strategy:
      matrix:
        arch: ["x86", "x64"]

    steps:
    - uses: actions/checkout@v2

    - name: Set up MinGW
      uses: egor-tensin/setup-mingw@v2
      with:
        platform: ${{ matrix.arch }} 

    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9

    - name: Build x64 source and tests
      if: matrix.arch == 'x64'
      run: python3 build.py --build-tests
    
    - name: Run x64 tests
      if: matrix.arch == 'x64'
      run: python3 build.py --run-tests
    
    - name: Build x86 source and tests
      if: matrix.arch != 'x64'
      run: python3 build.py -m32 --build-tests
    
    - name: Run x86 tests
      if: matrix.arch != 'x64'
      run: python3 build.py -m32 --run-tests

    #- name: Upload dist
      #uses: actions/upload-artifact@v2
      #with:
        #name: dist-MinGW
        #path: dist/
