name: MinGW

on:
  push:
    branches: [ main ]
    paths-ignore:
    - 'docs/**'
    - 'assets/**'
    - '.gitattributes'
    - '.gitignore'
    - 'LICENSE'
    - 'README.md'
  pull_request:
    branches: [ main ]
    paths-ignore:
    - 'docs/**'
    - 'assets/**'
    - '.gitattributes'
    - '.gitignore'
    - 'LICENSE'
    - 'README.md'

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up MinGW
      uses: egor-tensin/setup-mingw@v2
      with:
        platform: x64

    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9

    - name: Build source and tests
      run: python3 build.py --build-tests
    
    - name: Run tests
      run: python3 build.py --run-tests

    #- name: Upload dist
      #uses: actions/upload-artifact@v2
      #with:
        #name: dist-MinGW
        #path: dist/
