name: MSVC

on:
  push:
    branches: [ main ]
    paths-ignore:
    - 'docs/**'
    - 'assets/**'
    - '.gitattributes'
    - '.gitignore'
    - 'LICENSE'
    - 'README.md'
    - '.github/workflows/mingw-build.yml'
    - '.github/workflows/ubuntu-build.yml'
    - '.github/workflows/macos-build.yml'
  pull_request:
    branches: [ main ]
    paths-ignore:
    - 'docs/**'
    - 'assets/**'
    - '.gitattributes'
    - '.gitignore'
    - 'LICENSE'
    - 'README.md'
    - '.github/workflows/mingw-build.yml'
    - '.github/workflows/ubuntu-build.yml'
    - '.github/workflows/macos-build.yml'


jobs:
  build:
    runs-on: windows-latest

    strategy:
      fail-fast: false  # if a particular matrix build fails, don't skip the rest
      matrix:
        arch: ["x86", "x64"]

    steps:
    - uses: actions/checkout@v2

    - name: Add MSBuild to PATH
      uses: microsoft/setup-msbuild@v1

    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9

    - name: Build source and tests
      run: python3 build.py --msvc --build-tests --arch=${{matrix.arch}}
    
    - name: Run tests
      run: python3 build.py --msvc --run-tests --arch=${{matrix.arch}}
    
    - name: Check dist
      run: |
        .\\dist\\MSVC-${{matrix.arch}}-Release\\kcr.exe -V
        .\\dist\\MSVC-${{matrix.arch}}-Release\\kcr.exe --lex --ast test\\test_script.kh

    # - name: Upload dist
    # uses: actions/upload-artifact@v2
    # with:
    #   name: dist-MSVC
    #   path: dist/MSVC-${{matrix.arch}}-Release
