name: MSVC

on:
  push:
    branches: [ main ]
    paths-ignore:
    - 'docs/**'
    - 'assets/**'
    - '.gitattributes'
    - '.gitignore'
    - 'LICENSE'
    - 'README.md'
    - '.github/workflows/mingw-build.yml'
    - '.github/workflows/ubuntu-build.yml'
  pull_request:
    branches: [ main ]
    paths-ignore:
    - 'docs/**'
    - 'assets/**'
    - '.gitattributes'
    - '.gitignore'
    - 'LICENSE'
    - 'README.md'
    - '.github/workflows/mingw-build.yml'
    - '.github/workflows/ubuntu-build.yml'

env:
  # Path to the solution file relative to the root of the project.
  SOLUTION_FILE: Kithare.sln

jobs:
  build:
    runs-on: windows-latest

    strategy:
      matrix:
        arch: ["x86", "x64"]

    steps:
    - uses: actions/checkout@v2

    - name: Add MSBuild to PATH
      uses: microsoft/setup-msbuild@v1

    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9

    - name: Install SDL dependencies
      run: python build.py --msvc

    - name: Build source and tests
      working-directory: ${{env.GITHUB_WORKSPACE}}
      run: msbuild /m /p:Configuration=Release /p:Platform=${{matrix.arch}} ${{env.SOLUTION_FILE}}

    - name: Run x86 tests
      if: matrix.arch == 'x86'
      run: python build.py -m32 --msvc --run-tests

    - name: Run x64 tests
      if: matrix.arch == 'x64'
      run: python build.py --msvc --run-tests

    #- name: Upload dist
      #uses: actions/upload-artifact@v2
      #with:
        #name: dist-MSVC
        #path: dist/MSVC-x64-Release
